title: "KeJun blog"
description: "KeJun blog"
url: https://blog.kejun.space/
baseurl: 
author: "KeJun"
lang: "zh-CN"
paginate: 5
paginate_path: "/blog/page:num/"

markdown: kramdown
theme: jekyll-theme-mdui
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - node_modules
